spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54323/scrumproject
  application:
    name: scrum-project-service-API

env: "local"
