spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:54323/scrumproject
  application:
    name: scrum-project-service-API

env: "local"

server:
  #端口号
  port: 8001
#  address: 10.144.78.161