apiVersion: v1
kind: Service
metadata:
  name: scrumprojectservice-deployment
spec:
  type: LoadBalancer
  selector:
    app: scrumprojectservice-deployment
  ports:
  - port: 8002
    targetPort: 8080
